/* 
Inser employee data into main table
for this the following are different input parameters and it has 2 out parameters 
here the job id and pincode has a reference keys in job table and states table
*/
CREATE OR REPLACE PROCEDURE insert_employee(
    v_fname      IN employees_info.first_name%TYPE,
    v_lname      IN employees_info.last_name%TYPE,
    v_gender     IN employees_info.gender%TYPE,
    v_mail       IN employees_info.mail%TYPE,
    n_phone      IN employees_info.phone%TYPE,
    n_jID        IN employees_info.job_ID%TYPE,
    v_addr       IN employees_info.address%TYPE,
    n_picode     IN employees_info.pincode%TYPE,
    d_hire_date  IN employees_info.hire_date%TYPE,
    o_status     OUT NUMBER,  
    o_message    OUT varchar2
) IS
BEGIN
    --Main query to insert data into the table
    INSERT INTO employees_info (employee_id,first_name,last_name,gender,mail,phone,job_ID,address,pincode,hire_date) 
    VALUES (emp_pk.nextval,v_fname,v_lname,v_gender,v_mail,n_phone,n_jID,v_addr,n_picode,d_hire_date); 
    -- Primary key is generated by using sequence
    COMMIT; --to save the insert record
    o_status:=1;    --represents successful state
    o_message:='Succesfully Inserted!'; --message
    
EXCEPTION
    WHEN dup_val_on_index THEN
        o_status:=0;    -- represents failure state
        o_message:='Already exist!'; --message
    WHEN VALUE_ERROR THEN 
        o_status:=0;    -- represents failure state
        o_message:='Unexpected data type error Occured!';    --message
    WHEN OTHERS THEN
        o_status:=0;    -- represents failure state
        o_message:='error occured'; --message
END;
/

--execution 
declare
    first_name employees_info.first_name%type:='&enter_first_name';
    last_name employees_info.last_name%type:='&enter_last_name';
    gender employees_info.gender%type:='&gender';
    mail employees_info.mail%type:='&mail_id';
    phone employees_info.phone%type:=&phone;
    job_id employees_info.job_id%type:='&job_type';
    address employees_info.address%type:='&address';
    pincode employees_info.pincode%type:=&pincode;
    hire_date employees_info.hire_date%type:='&hire_date';
    o_status number(10);
    o_message varchar2(50);
begin
insert_employee(first_name,last_name,gender,mail,phone,job_id,address,pincode,hire_date,o_status,o_message);
dbms_output.put_line(o_status);
dbms_output.put_line(o_message);
end;
/

SELECT * FROM employees_info;
